"""
Merge SLP Normal Poses with Fall Detection Dataset
Creates unified YOLO dataset with both fall and normal classes

Usage:
    python scripts/merge_slp_with_falls.py

Output:
    - datasets/vision/yolo_merged/train/
    - datasets/vision/yolo_merged/val/
    - datasets/vision/yolo_merged/test/
    - datasets/vision/yolo_merged/dataset.yaml
"""

import os
import json
import shutil
from pathlib import Path

try:
    from tqdm import tqdm
except ImportError:
    tqdm = lambda x, **kwargs: x


def merge_datasets():
    """Merge SLP and fall detection datasets"""
    
    print("\n" + "="*70)
    print("MERGING SLP + FALL DETECTION DATASETS")
    print("="*70)
    
    # Paths
    slp_images = 'datasets/vision/processed/slp/images'
    slp_labels = 'datasets/vision/processed/slp/labels'
    falls_root = 'datasets/vision/yolo'  # Existing fall dataset
    output_root = 'datasets/vision/yolo_merged'
    
    # Check inputs exist
    if not os.path.exists(slp_images):
        print(f"[X] ERROR: SLP not preprocessed. Run: python scripts/preprocess_slp.py")
        return
    
    if not os.path.exists(falls_root):
        print(f"[X] ERROR: Fall dataset not found. Run: python scripts/prepare_yolo_dataset.py")
        return
    
    # Create output structure
    for split in ['train', 'val', 'test']:
        os.makedirs(os.path.join(output_root, split, 'images'), exist_ok=True)
        os.makedirs(os.path.join(output_root, split, 'labels'), exist_ok=True)
    
    stats = {'train': {'fall': 0, 'normal': 0},
             'val': {'fall': 0, 'normal': 0},
             'test': {'fall': 0, 'normal': 0}}
    
    # Step 1: Copy existing fall detection data
    print("\n[*] Step 1: Copying fall detection dataset...")
    for split in ['train', 'val', 'test']:
        src_img = os.path.join(falls_root, split, 'images')
        src_lbl = os.path.join(falls_root, split, 'labels')
        dst_img = os.path.join(output_root, split, 'images')
        dst_lbl = os.path.join(output_root, split, 'labels')
        
        if os.path.exists(src_img):
            images = [f for f in os.listdir(src_img) if f.endswith(('.jpg', '.png'))]
            for img in tqdm(images, desc=f"  {split}"):
                shutil.copy2(os.path.join(src_img, img), os.path.join(dst_img, img))
                
                # Copy label
                lbl = img.replace('.jpg', '.txt').replace('.png', '.txt')
                if os.path.exists(os.path.join(src_lbl, lbl)):
                    shutil.copy2(os.path.join(src_lbl, lbl), os.path.join(dst_lbl, lbl))
                    
                    # Count class (0=normal, 1=fall in original)
                    with open(os.path.join(dst_lbl, lbl)) as f:
                        label = int(f.read().split()[0])
                        if label == 1:
                            stats[split]['fall'] += 1
                        else:
                            stats[split]['normal'] += 1
    
    # Step 2: Split and add SLP data
    print("\n[*] Step 2: Adding SLP normal poses...")
    
    slp_imgs = sorted([f for f in os.listdir(slp_images) if f.endswith('.png')])
    total_slp = len(slp_imgs)
    
    # Split: 70% train, 15% val, 15% test
    train_end = int(total_slp * 0.70)
    val_end = train_end + int(total_slp * 0.15)
    
    splits_data = {
        'train': slp_imgs[:train_end],
        'val': slp_imgs[train_end:val_end],
        'test': slp_imgs[val_end:]
    }
    
    for split, imgs in splits_data.items():
        dst_img = os.path.join(output_root, split, 'images')
        dst_lbl = os.path.join(output_root, split, 'labels')
        
        for img in tqdm(imgs, desc=f"  {split}"):
            # Copy image
            shutil.copy2(os.path.join(slp_images, img), os.path.join(dst_img, img))
            
            # Copy label
            lbl = img.replace('.png', '.txt')
            if os.path.exists(os.path.join(slp_labels, lbl)):
                shutil.copy2(os.path.join(slp_labels, lbl), os.path.join(dst_lbl, lbl))
                stats[split]['normal'] += 1
    
    # Step 3: Create dataset.yaml
    print("\n[*] Step 3: Creating dataset.yaml...")
    
    yaml_content = f"""# Merged Fall Detection + SLP Dataset
# Generated by merge_slp_with_falls.py

path: ../datasets/vision/yolo_merged  # dataset root
train: train/images
val: val/images
test: test/images

# Classes
nc: 2  # number of classes
names: ['normal', 'fall']  # class names

# Statistics
# Train: {stats['train']['normal'] + stats['train']['fall']} images ({stats['train']['normal']} normal, {stats['train']['fall']} fall)
# Val:   {stats['val']['normal'] + stats['val']['fall']} images ({stats['val']['normal']} normal, {stats['val']['fall']} fall)
# Test:  {stats['test']['normal'] + stats['test']['fall']} images ({stats['test']['normal']} normal, {stats['test']['fall']} fall)
"""
    
    yaml_path = os.path.join(output_root, 'dataset.yaml')
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    
    print(f"[OK] Created: {yaml_path}")
    
    # Print summary
    print("\n" + "="*70)
    print("MERGE COMPLETE")
    print("="*70)
    print(f"\nDataset location: {output_root}/")
    print(f"\nClass distribution:")
    print(f"\n{'Split':<10} {'Normal':<10} {'Fall':<10} {'Total':<10}")
    print("-" * 40)
    for split in ['train', 'val', 'test']:
        normal = stats[split]['normal']
        fall = stats[split]['fall']
        total = normal + fall
        print(f"{split:<10} {normal:<10,} {fall:<10,} {total:<10,}")
    
    total_normal = sum(s['normal'] for s in stats.values())
    total_fall = sum(s['fall'] for s in stats.values())
    total_all = total_normal + total_fall
    print("-" * 40)
    print(f"{'TOTAL':<10} {total_normal:<10,} {total_fall:<10,} {total_all:<10,}")
    
    print("\n" + "="*70)
    print("Next steps:")
    print("  1. Upload to Kaggle as new dataset")
    print("  2. Train YOLO model with 2 classes")
    print("  3. Update config.yaml with new model path")
    print("="*70 + "\n")


if __name__ == '__main__':
    merge_datasets()








